development:
  adapter: postgresql
  encoding: unicode
  database: xgb_shiko
  pool: 5
  username: xgb_shiko
  password: 8ea1e9ceeyui
  host: postgres48.1gb.ru

production:
  adapter: postgresql
  encoding: unicode
  database: xgb_shiko
  pool: 5
  username: xgb_shiko
  password: 8ea1e9ceeyui
  host: postgres48.1gb.ru
