# Стас не удаляй!
#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: hu_shiko
  pool: 5
  username: hu_shiko
  password: eef6427829fa1fb83dc06ce09021c81d674319
  host: 127.0.0.1

development:
  adapter: postgresql
  encoding: unicode
  database: hu_shiko
  pool: 5
  username: hu_shiko
  password: eef6427829fa1fb83dc06ce09021c81d674319
  host: 127.0.0.1
